handle putenv arg constness in configure

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -2341,6 +2341,66 @@ _ACEOF
 
 fi
 
+
+echo "$as_me:$LINENO: checking for type of string parameter to putenv" >&5
+echo $ECHO_N "checking for type of string parameter to putenv... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+    #include <stdlib.h>
+
+int
+main ()
+{
+
+    putenv((const char *)0);
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  rcl_putenv_string_const="1"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+rcl_putenv_string_const="0"
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+if test X$rcl_putenv_string_const = X1 ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define PUTENV_ARG_CONST 1
+_ACEOF
+
+fi
+
 #### Look for Xapian
 # Extract the first word of "xapian-config", so it can be a program name with args.
 set dummy xapian-config; ac_word=$2
